apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "alertlens.fullname" . }}
  labels:
    {{- include "alertlens.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.state.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.state.size }}
